/**
 * Module Registration for Global Search
 * AMS ERP Global Search System
 *
 * Registers all searchable entities with the SearchRegistry.
 * New modules simply add their registration here.
 */

const registry = require('./searchRegistry');

function registerAll() {
  const models = require('../models');

  registry.registerModule({
    entityType: 'lead',
    moduleName: 'Leads',
    model: models.Lead,
    permissionKey: 'leads',
    icon: 'UserPlus',
    priority: 200,
    searchWeight: 10,
    titleField: 'customerName',
    subtitleField: 'leadNo',
    searchableFields: ['customerName', 'email', 'phone', 'city', 'leadNo', 'status', 'source', 'type', 'priority', 'description', 'notes'],
    keywordFields: ['leadNo', 'phone', 'email', 'customerName'],
    highlightFields: ['customerName', 'phone', 'city'],
    assignmentFields: ['assignedTo'],
    creatorField: 'createdBy',
    statusField: 'status',
    conditions: { deletedAt: null },
    urlFn: (doc) => {
      let url = `/leads?search=${encodeURIComponent(doc.customerName || '')}&open=${doc._id}`;
      if (doc.convertedToCustomer) url += '&converted=true';
      return url;
    },
  });

  registry.registerModule({
    entityType: 'customer',
    moduleName: 'Customers',
    model: models.Customer,
    permissionKey: 'customers',
    icon: 'Users',
    priority: 200,
    searchWeight: 9,
    titleField: 'name',
    subtitleField: 'companyName',
    searchableFields: ['firstName', 'lastName', 'companyName', 'email', 'phone', 'customerCode', 'address', 'city'],
    keywordFields: ['customerCode', 'phone', 'email'],
    highlightFields: ['firstName', 'lastName', 'companyName', 'phone'],
    assignmentFields: ['assignedTo'],
    creatorField: 'createdBy',
    statusField: 'isActive',
    conditions: { deletedAt: null },
    urlFn: (doc) => {
      const name = [doc.firstName, doc.lastName].filter(Boolean).join(' ') || doc.companyName || 'Customer';
      return `/customers?search=${encodeURIComponent(name)}&open=${doc._id}`;
    },
    getSearchDocument: (doc) => {
      const name = [doc.firstName, doc.lastName].filter(Boolean).join(' ') || doc.companyName || 'Customer';
      return {
        entityType: 'customer',
        moduleName: 'Customers',
        entityId: String(doc._id),
        title: name,
        subtitle: doc.companyName || doc.email || '',
        searchableText: [name, doc.email, doc.phone, doc.companyName, doc.customerCode, doc.address, doc.city].filter(Boolean).join(' '),
        keywords: [doc.customerCode, doc.phone, doc.email].filter(Boolean),
        url: `/customers?search=${encodeURIComponent(name)}&open=${doc._id}`,
        permissionKey: 'customers',
        assignedTo: doc.assignedTo ? String(doc.assignedTo._id || doc.assignedTo) : null,
        createdBy: doc.createdBy ? String(doc.createdBy._id || doc.createdBy) : null,
        status: doc.isActive ? 'active' : 'inactive',
        isActive: !doc.deletedAt,
        score: 9,
        metadata: { email: doc.email, phone: doc.phone },
      };
    },
  });

  registry.registerModule({
    entityType: 'invoice',
    moduleName: 'Invoices',
    model: models.Invoice,
    permissionKey: 'invoices',
    icon: 'FileText',
    priority: 300,
    searchWeight: 8,
    titleField: 'invoiceNumber',
    subtitleField: 'status',
    searchableFields: ['invoiceNumber', 'status', 'totalAmount', 'customer.firstName', 'customer.lastName', 'notes'],
    keywordFields: ['invoiceNumber'],
    highlightFields: ['invoiceNumber', 'customer.firstName', 'customer.lastName'],
    assignmentFields: ['createdBy'],
    creatorField: 'createdBy',
    statusField: 'status',
    populate: 'customer',
    conditions: { deletedAt: null, cancelledAt: null },
    urlFn: (doc) => `/invoices?search=${encodeURIComponent(doc.invoiceNumber || '')}&open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'order',
    moduleName: 'Orders',
    model: models.SalesOrder,
    permissionKey: 'orders',
    icon: 'ShoppingCart',
    priority: 300,
    searchWeight: 7,
    titleField: 'orderNumber',
    subtitleField: 'status',
    searchableFields: ['orderNumber', 'status', 'totalAmount', 'customer.firstName', 'customer.lastName', 'notes'],
    keywordFields: ['orderNumber'],
    highlightFields: ['orderNumber'],
    assignmentFields: ['createdBy'],
    creatorField: 'createdBy',
    statusField: 'status',
    populate: 'customer',
    conditions: { deletedAt: null },
    urlFn: (doc) => `/orders?search=${encodeURIComponent(doc.orderNumber || '')}&open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'quotation',
    moduleName: 'Quotations',
    model: models.Quotation,
    permissionKey: 'quotations',
    icon: 'FileText',
    priority: 300,
    searchWeight: 7,
    titleField: 'quotationNumber',
    subtitleField: 'status',
    searchableFields: ['quotationNumber', 'status', 'totalAmount', 'customer.firstName', 'customer.lastName'],
    keywordFields: ['quotationNumber'],
    highlightFields: ['quotationNumber'],
    assignmentFields: ['createdBy'],
    creatorField: 'createdBy',
    statusField: 'status',
    populate: 'customer',
    conditions: { deletedAt: null },
    urlFn: (doc) => `/quotations?search=${encodeURIComponent(doc.quotationNumber || '')}&open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'booking',
    moduleName: 'Bookings',
    model: models.Booking,
    permissionKey: 'booking',
    icon: 'CalendarCheck',
    priority: 300,
    searchWeight: 7,
    titleField: 'bookingNumber',
    subtitleField: 'status',
    searchableFields: ['bookingNumber', 'status', 'totalAmount', 'customer.firstName', 'customer.lastName'],
    keywordFields: ['bookingNumber'],
    highlightFields: ['bookingNumber'],
    assignmentFields: ['createdBy'],
    creatorField: 'createdBy',
    statusField: 'status',
    populate: 'customer',
    conditions: { deletedAt: null },
    urlFn: (doc) => `/booking?search=${encodeURIComponent(doc.bookingNumber || '')}&open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'vehicle',
    moduleName: 'Vehicles',
    model: models.Vehicle,
    permissionKey: 'vehicles',
    icon: 'Truck',
    priority: 400,
    searchWeight: 8,
    titleField: 'registrationNumber',
    subtitleField: 'make',
    searchableFields: ['vin', 'chassisNumber', 'engineNumber', 'registrationNumber', 'make', 'model', 'variant', 'color', 'stockNumber', 'status', 'warehouse'],
    keywordFields: ['vin', 'registrationNumber', 'chassisNumber', 'engineNumber', 'stockNumber'],
    highlightFields: ['registrationNumber', 'vin', 'make', 'model'],
    assignmentFields: ['assignedTo'],
    creatorField: 'createdBy',
    statusField: 'status',
    conditions: {},
    urlFn: (doc) => `/vehicles?search=${encodeURIComponent(doc.registrationNumber || doc.vin || '')}&open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'part',
    moduleName: 'Parts',
    model: models.Part,
    permissionKey: 'parts',
    icon: 'Package',
    priority: 400,
    searchWeight: 6,
    titleField: 'name',
    subtitleField: 'partCode',
    searchableFields: ['name', 'partCode', 'description', 'category', 'supplier', 'sku', 'barcode', 'quantity', 'price'],
    keywordFields: ['partCode', 'sku', 'barcode'],
    highlightFields: ['name', 'partCode'],
    assignmentFields: [],
    creatorField: 'createdBy',
    statusField: 'isActive',
    conditions: {},
    urlFn: (doc) => `/parts?search=${encodeURIComponent(doc.name || '')}&open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'employee',
    moduleName: 'Employees',
    model: models.Employee,
    permissionKey: 'hr/employees',
    icon: 'Briefcase',
    priority: 500,
    searchWeight: 7,
    titleField: 'firstName',
    subtitleField: 'employeeCode',
    searchableFields: ['firstName', 'lastName', 'email', 'phone', 'employeeCode', 'designation', 'department', 'employeeType'],
    keywordFields: ['employeeCode', 'phone', 'email'],
    highlightFields: ['firstName', 'lastName', 'employeeCode'],
    assignmentFields: ['assignedTo'],
    creatorField: 'createdBy',
    statusField: 'isActive',
    conditions: { isDeleted: { $ne: true } },
    getSearchDocument: (doc) => {
      const name = [doc.firstName, doc.lastName].filter(Boolean).join(' ') || doc.employeeCode || 'Employee';
      return {
        entityType: 'employee',
        moduleName: 'Employees',
        entityId: String(doc._id),
        title: name,
        subtitle: doc.designation || doc.employeeCode || '',
        searchableText: [name, doc.email, doc.phone, doc.employeeCode, doc.designation, doc.department].filter(Boolean).join(' '),
        keywords: [doc.employeeCode, doc.phone, doc.email].filter(Boolean),
        url: `/hr/employees?search=${encodeURIComponent(name)}&open=${doc._id}`,
        permissionKey: 'hr/employees',
        assignedTo: doc.assignedTo ? String(doc.assignedTo._id || doc.assignedTo) : null,
        createdBy: doc.createdBy ? String(doc.createdBy._id || doc.createdBy) : null,
        status: doc.isActive ? 'active' : 'inactive',
        isActive: doc.isDeleted !== true,
        score: 7,
        metadata: { email: doc.email, designation: doc.designation },
      };
    },
  });

  registry.registerModule({
    entityType: 'leave',
    moduleName: 'Leaves',
    model: models.Leave,
    permissionKey: 'hr/leaves',
    icon: 'Calendar',
    priority: 600,
    searchWeight: 4,
    titleField: 'type',
    subtitleField: 'status',
    searchableFields: ['type', 'status', 'reason', 'employee.firstName', 'employee.lastName'],
    keywordFields: [],
    highlightFields: ['type', 'employee.firstName', 'employee.lastName'],
    assignmentFields: ['assignedTo'],
    creatorField: 'createdBy',
    statusField: 'status',
    populate: 'employee',
    conditions: {},
    urlFn: (doc) => `/hr/leaves?open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'expense',
    moduleName: 'Expenses',
    model: models.Expense,
    permissionKey: 'hr/expenses',
    icon: 'DollarSign',
    priority: 600,
    searchWeight: 4,
    titleField: 'category',
    subtitleField: 'status',
    searchableFields: ['category', 'status', 'description', 'amount', 'employee.firstName', 'employee.lastName'],
    keywordFields: [],
    highlightFields: ['category', 'description'],
    assignmentFields: ['assignedTo'],
    creatorField: 'createdBy',
    statusField: 'status',
    populate: 'employee',
    conditions: {},
    urlFn: (doc) => `/hr/expenses?open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'ledger',
    moduleName: 'Ledger',
    model: models.LedgerEntry,
    permissionKey: 'hr/ledger',
    icon: 'BookOpen',
    priority: 700,
    searchWeight: 3,
    titleField: 'account',
    subtitleField: 'type',
    searchableFields: ['account', 'type', 'description', 'reference', 'amount', 'date'],
    keywordFields: ['reference'],
    highlightFields: ['account', 'description', 'reference'],
    assignmentFields: ['createdBy'],
    creatorField: 'createdBy',
    statusField: 'status',
    conditions: {},
    urlFn: (doc) => `/hr/ledger?open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'user',
    moduleName: 'Users',
    model: models.User,
    permissionKey: 'admin/users',
    icon: 'UserCircle',
    priority: 100,
    searchWeight: 5,
    titleField: 'firstName',
    subtitleField: 'email',
    searchableFields: ['firstName', 'lastName', 'email', 'phone', 'role.displayName', 'department'],
    keywordFields: ['email', 'phone'],
    highlightFields: ['firstName', 'lastName', 'email'],
    assignmentFields: [],
    creatorField: '',
    statusField: 'isActive',
    conditions: {},
    urlFn: (doc) => `/admin/users?search=${encodeURIComponent([doc.firstName, doc.lastName].filter(Boolean).join(' ') || doc.email)}&open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'department',
    moduleName: 'Departments',
    model: models.Department,
    permissionKey: 'admin/departments',
    icon: 'Building2',
    priority: 800,
    searchWeight: 3,
    titleField: 'name',
    subtitleField: 'description',
    searchableFields: ['name', 'description', 'manager.firstName', 'manager.lastName'],
    keywordFields: [],
    highlightFields: ['name'],
    assignmentFields: [],
    creatorField: '',
    statusField: 'isActive',
    conditions: {},
    urlFn: (doc) => `/admin/departments?open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'service_appointment',
    moduleName: 'Service Appointments',
    model: models.ServiceAppointment,
    permissionKey: 'service',
    icon: 'Wrench',
    priority: 500,
    searchWeight: 6,
    titleField: 'serviceType',
    subtitleField: 'status',
    searchableFields: ['serviceType', 'status', 'appointmentDate', 'customer.firstName', 'customer.lastName', 'vehicle.registrationNumber', 'notes'],
    keywordFields: ['vehicle.registrationNumber'],
    highlightFields: ['serviceType', 'customer.firstName', 'customer.lastName'],
    assignmentFields: ['assignedTo'],
    creatorField: 'createdBy',
    statusField: 'status',
    populate: ['customer', 'vehicle'],
    conditions: {},
    urlFn: (doc) => `/service/appointments?open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'job_card',
    moduleName: 'Job Cards',
    model: models.JobCard,
    permissionKey: 'service',
    icon: 'ClipboardList',
    priority: 500,
    searchWeight: 6,
    titleField: 'status',
    subtitleField: 'serviceType',
    searchableFields: ['status', 'serviceType', 'customer.firstName', 'customer.lastName', 'vehicle.registrationNumber', 'notes'],
    keywordFields: ['vehicle.registrationNumber'],
    highlightFields: ['status', 'customer.firstName', 'customer.lastName'],
    assignmentFields: ['assignedTo'],
    creatorField: 'createdBy',
    statusField: 'status',
    populate: ['customer', 'vehicle'],
    conditions: {},
    urlFn: (doc) => `/service/job-cards?open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'warehouse',
    moduleName: 'Warehouses',
    model: models.Warehouse,
    permissionKey: 'warehouses',
    icon: 'Warehouse',
    priority: 700,
    searchWeight: 3,
    titleField: 'warehouseName',
    subtitleField: 'city',
    searchableFields: ['warehouseName', 'code', 'location', 'city', 'description'],
    keywordFields: ['code'],
    highlightFields: ['warehouseName', 'city'],
    assignmentFields: [],
    creatorField: '',
    statusField: 'isActive',
    conditions: {},
    urlFn: (doc) => `/warehouses?open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'email_template',
    moduleName: 'Email Templates',
    model: models.EmailTemplate,
    permissionKey: 'email',
    icon: 'Mail',
    priority: 800,
    searchWeight: 3,
    titleField: 'name',
    subtitleField: 'subject',
    searchableFields: ['name', 'subject', 'description', 'category'],
    keywordFields: [],
    highlightFields: ['name', 'subject'],
    assignmentFields: [],
    creatorField: 'createdBy',
    statusField: 'isActive',
    conditions: {},
    urlFn: (doc) => `/email/templates?open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'pdf_template',
    moduleName: 'PDF Templates',
    model: models.PdfTemplate,
    permissionKey: 'pdf-management',
    icon: 'FileText',
    priority: 800,
    searchWeight: 3,
    titleField: 'name',
    subtitleField: 'documentType',
    searchableFields: ['name', 'documentType', 'description'],
    keywordFields: [],
    highlightFields: ['name', 'documentType'],
    assignmentFields: [],
    creatorField: 'createdBy',
    statusField: 'isActive',
    conditions: {},
    urlFn: (doc) => `/pdf-management?open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'page',
    moduleName: 'Pages',
    model: models.Page,
    permissionKey: 'server-management',
    icon: 'Layout',
    priority: 900,
    searchWeight: 2,
    titleField: 'label',
    subtitleField: 'path',
    searchableFields: ['label', 'name', 'path', 'module', 'group'],
    keywordFields: ['path', 'name'],
    highlightFields: ['label', 'path'],
    assignmentFields: [],
    creatorField: '',
    statusField: 'isActive',
    conditions: { isActive: { $ne: false } },
    urlFn: (doc) => doc.path || `/${doc.name}`,
  });

  registry.registerModule({
    entityType: 'payment_method',
    moduleName: 'Payment Methods',
    model: models.PaymentMethod,
    permissionKey: 'payment-methods',
    icon: 'CreditCard',
    priority: 800,
    searchWeight: 2,
    titleField: 'name',
    subtitleField: 'type',
    searchableFields: ['name', 'type', 'description'],
    keywordFields: [],
    highlightFields: ['name'],
    assignmentFields: [],
    creatorField: '',
    statusField: 'isActive',
    conditions: {},
    urlFn: (doc) => `/payment-methods?open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'status_item',
    moduleName: 'Status Items',
    model: models.StatusItem,
    permissionKey: 'admin/statuses',
    icon: 'CheckCircle2',
    priority: 900,
    searchWeight: 2,
    titleField: 'label',
    subtitleField: 'value',
    searchableFields: ['label', 'value', 'description', 'module'],
    keywordFields: [],
    highlightFields: ['label', 'value'],
    assignmentFields: [],
    creatorField: '',
    statusField: 'isActive',
    conditions: {},
    urlFn: (doc) => `/admin/statuses?open=${doc._id}`,
  });

  registry.registerModule({
    entityType: 'file_upload',
    moduleName: 'Uploads',
    model: models.FileUpload,
    permissionKey: 'files',
    icon: 'File',
    priority: 900,
    searchWeight: 2,
    titleField: 'originalName',
    subtitleField: 'mimeType',
    searchableFields: ['originalName', 'fileName', 'mimeType', 'module'],
    keywordFields: ['fileName', 'originalName'],
    highlightFields: ['originalName'],
    assignmentFields: ['uploadedBy'],
    creatorField: 'uploadedBy',
    statusField: '',
    conditions: {},
    urlFn: (doc) => `/uploads/${doc.fileName}`,
  });
}

module.exports = { registerAll };
