const {SearchDocument,Customer,Invoice,SalesOrder,Quotation,Booking,Part,Vehicle,Page}=require('../models');
const Log=require('../models/mongo/Log.model');
const name=c=>[c?.firstName,c?.lastName].filter(Boolean).join(' ')||c?.companyName||'';
const docs=[];
function add(entityType,entityId,title,subtitle,searchableText,url,metadata={}){docs.push({entityType,entityId:String(entityId),title,subtitle,searchableText,url,metadata,isActive:true,updatedAt:new Date()})}
async function rebuild(){docs.length=0;const [customers,invoices,orders,quotations,bookings,parts,vehicles,pages]=await Promise.all([Customer.find({deletedAt:null}).lean(),Invoice.find().populate('customer','firstName lastName').lean(),SalesOrder.find().populate('customer','firstName lastName').lean(),Quotation.find().populate('customer','firstName lastName').lean(),Booking.find().populate('customer','firstName lastName').lean(),Part.find().lean(),Vehicle.find().lean(),Page.find({isActive:{$ne:false}}).lean()]);customers.forEach(d=>{const n=name(d);add('customer',d._id,n,d.email,[n,d.email,d.phone,d.customerCode,d.companyName].join(' '),`/customers/${d._id}`,{email:d.email,phone:d.phone})});invoices.forEach(d=>add('invoice',d._id,`Invoice ${d.invoiceNumber||''}`,d.status,[d.invoiceNumber,d.status,name(d.customer),d.totalAmount].join(' '),`/sales/invoices?highlight=${d._id}`,{invoiceNumber:d.invoiceNumber,status:d.status}));orders.forEach(d=>add('order',d._id,`Order ${d.orderNumber||''}`,d.status,[d.orderNumber,d.status,name(d.customer),d.notes].join(' '),`/sales/orders?highlight=${d._id}`,{orderNumber:d.orderNumber,status:d.status}));quotations.forEach(d=>add('quotation',d._id,`Quotation ${d.quotationNumber||''}`,d.status,[d.quotationNumber,d.status,name(d.customer)].join(' '),`/sales/quotations?highlight=${d._id}`,{}));bookings.forEach(d=>add('booking',d._id,`Booking ${d.bookingNumber||''}`,d.status,[d.bookingNumber,d.status,name(d.customer)].join(' '),`/sales/bookings?highlight=${d._id}`,{}));parts.forEach(d=>add('product',d._id,d.name||d.partCode,d.partCode,d.name+' '+d.partCode+' '+d.description,`/parts?search=${encodeURIComponent(d.name||'')}`,{}));vehicles.forEach(d=>add('vehicle',d._id,d.registrationNumber||d.stockNumber||d.vin,'Vehicle',[d.vin,d.registrationNumber,d.stockNumber,d.make,d.model].join(' '),`/vehicles?search=${encodeURIComponent(d.registrationNumber||d.vin||'')}`,{}));pages.forEach(d=>add('page',d._id,d.label||d.name,d.path,[d.label,d.name,d.path,d.module].join(' '),d.path,{}));await SearchDocument.deleteMany({});if(docs.length)await SearchDocument.insertMany(docs,{ordered:false});return docs.length}
async function rebuildWithLog(actor){try{const count=await rebuild();await Log.create({module:'search',action:'index_rebuild',method:'POST',endpoint:'internal/search/rebuild',user:{id:String(actor||'')},success:true,statusCode:200,metadata:{count}});return count}catch(error){await Log.create({module:'search',action:'index_rebuild_failed',method:'POST',endpoint:'internal/search/rebuild',user:{id:String(actor||'')},success:false,statusCode:500,error:{name:error.name,message:error.message}}).catch(()=>{});throw error}}
let rebuildTimer=null;const scheduleRebuild=actor=>{if(rebuildTimer)clearTimeout(rebuildTimer);rebuildTimer=setTimeout(()=>rebuildWithLog(actor).catch(()=>{}),1500)};
module.exports={rebuildWithLog,scheduleRebuild};
