const pages = [
  { key: 'dashboard', label: 'Dashboard', path: '/dashboard', module: 'dashboard', icon: 'LayoutDashboard', group: 'Main', isCore: true, isActive: true },
  { key: 'leads', label: 'Leads', path: '/leads', module: 'crm', icon: 'Users', group: 'CRM', isCore: false, isActive: true },
  { key: 'customers', label: 'Customers', path: '/customers', module: 'crm', icon: 'Contact', group: 'CRM', isCore: false, isActive: true },
  { key: 'vehicles', label: 'Vehicles', path: '/vehicles', module: 'inventory', icon: 'Car', group: 'Inventory', isCore: false, isActive: true },
  { key: 'vehicle_master', label: 'Vehicle Master Data', path: '/vehicle-master', module: 'vehicle-master', icon: 'CarFront', group: 'Master Data', isCore: false, isActive: true },
  { key: 'vehicle_branding', label: 'Vehicle Branding', path: '/vehicle-branding', module: 'vehicle-branding', icon: 'Badge', group: 'Inventory', isCore: false, isActive: true },
  { key: 'parts', label: 'Parts Inventory', path: '/parts', module: 'parts', icon: 'Cog', group: 'Inventory', isCore: false, isActive: true },
  { key: 'warehouses', label: 'Warehouse Management', path: '/warehouses', module: 'warehouses', icon: 'Warehouse', group: 'Master Data', isCore: false, isActive: true },
  { key: 'quotations', label: 'Quotations', path: '/sales/quotations', module: 'sales', icon: 'FileText', group: 'Sales', isCore: false, isActive: true },
  { key: 'bookings', label: 'Bookings', path: '/sales/bookings', module: 'sales', icon: 'CalendarCheck', group: 'Sales', isCore: false, isActive: true },
  { key: 'sales', label: 'Sales', path: '/sales/orders', module: 'sales', icon: 'ClipboardList', group: 'Sales', isCore: false, isActive: true },
  { key: 'invoices', label: 'Invoices', path: '/sales/invoices', module: 'invoices', icon: 'Receipt', group: 'Sales', isCore: false, isActive: true },
  { key: 'payments', label: 'Payments', path: '/settings#payment-methods', module: 'payments', icon: 'CreditCard', group: 'ERP Settings', isCore: false, isActive: true },
  { key: 'services', label: 'Services', path: '/service/appointments', module: 'service', icon: 'Wrench', group: 'Service', isCore: false, isActive: true },
  { key: 'service_master', label: 'Service Master Data', path: '/service-master', module: 'service-master', icon: 'Settings', group: 'Master Data', isCore: false, isActive: true },
  { key: 'reports', label: 'Reports', path: '/reports', module: 'reports', icon: 'BarChart3', group: 'Reports', isCore: false, isActive: true },
  { key: 'employees', label: 'Employees', path: '/hr/employees', module: 'hr', icon: 'UserRound', group: 'HR & Finance', isCore: false, isActive: true },
  { key: 'payroll', label: 'Payroll', path: '/hr/payroll', module: 'payroll', icon: 'CircleDollarSign', group: 'HR & Finance', isCore: false, isActive: true },
  { key: 'leaves', label: 'Leaves', path: '/hr/leaves', module: 'leaves', icon: 'CalendarDays', group: 'HR & Finance', isCore: false, isActive: true },
  { key: 'expenses', label: 'Expenses', path: '/hr/expenses', module: 'expenses', icon: 'WalletCards', group: 'HR & Finance', isCore: false, isActive: true },
  { key: 'ledger', label: 'Ledger', path: '/hr/ledger', module: 'ledger', icon: 'BookOpen', group: 'HR & Finance', isCore: false, isActive: true },
  { key: 'settings', label: 'Settings', path: '/settings', module: 'settings', icon: 'Settings', group: 'ERP Settings', isCore: false, isActive: true },
  { key: 'erp_settings', label: 'ERP Settings', path: '/settings', module: 'erp-settings', icon: 'SlidersHorizontal', group: 'ERP Settings', isCore: false, isActive: true },
  { key: 'user_management', label: 'User Management', path: '/admin/users', module: 'users', icon: 'UsersRound', group: 'Master Data', isCore: false, isActive: true },
  { key: 'department_management', label: 'Department Management', path: '/admin/departments', module: 'departments', icon: 'Building2', group: 'Master Data', isCore: false, isActive: true },
  { key: 'status_management', label: 'Status Management', path: '/admin/statuses', module: 'statuses', icon: 'ListChecks', group: 'Master Data', isCore: false, isActive: true },
  { key: 'lead_master', label: 'Lead Master Data', path: '/lead-master', module: 'lead-master', icon: 'ListTree', group: 'Master Data', isCore: false, isActive: true },
  { key: 'sales_master', label: 'Sales Master Data', path: '/sales-master', module: 'sales-master', icon: 'PanelTop', group: 'Master Data', isCore: false, isActive: true },
  { key: 'profile', label: 'Profile', path: '/profile', module: 'profile', icon: 'UserCircle', group: 'Account', isCore: false, isActive: true },
  { key: 'order_form_upload', label: 'Order Form Upload', path: '/uploader/order-form', module: 'uploader', icon: 'UploadCloud', group: 'Uploader', isCore: false, isActive: true },
  { key: 'server_management', label: 'Server Management', path: '/server-management', module: 'server-management', icon: 'ServerCog', group: 'System', isCore: true, isActive: true }
];

export default pages;
