/**
 * Mirror of backend/constants/pages.js — the canonical page table (labels,
 * groups, icons and sidebar order). Regenerated from the backend table; do not
 * edit by hand. The server's Page collection is what the sidebar actually
 * renders; this copy only seeds Frontend Management's defaults.
 */
const pages = [
  { key: 'dashboard', label: 'Dashboard', path: '/dashboard', module: 'dashboard', icon: 'LayoutDashboard', group: 'Main', isCore: true, isActive: true, sortOrder: 0 },
  { key: 'master_data', label: 'Master Data', path: '/masterdata', module: 'master-data', icon: 'Database', group: 'Master Data', isCore: false, isActive: true, sortOrder: 1 },
  { key: 'leads', label: 'Leads', path: '/leads', module: 'crm', icon: 'Users', group: 'CRM', isCore: false, isActive: true, sortOrder: 2 },
  { key: 'customers', label: 'Customers', path: '/customers', module: 'crm', icon: 'Contact', group: 'CRM', isCore: false, isActive: true, sortOrder: 3 },
  { key: 'vehicles', label: 'Vehicles', path: '/vehicles', module: 'inventory', icon: 'Car', group: 'Inventory', isCore: false, isActive: true, sortOrder: 4 },
  { key: 'services', label: 'Services', path: '/service', module: 'service', icon: 'Wrench', group: 'Service', isCore: false, isActive: true, sortOrder: 5 },
  { key: 'vehicle_master', label: 'Vehicle Master Data', path: '/vehicle-master', module: 'vehicle-master', icon: 'CarFront', group: 'Master Data', isCore: false, isActive: true, sortOrder: 6 },
  { key: 'parts', label: 'Parts Inventory', path: '/parts', module: 'parts', icon: 'Cog', group: 'Inventory', isCore: false, isActive: true, sortOrder: 7 },
  { key: 'service_appointments', label: 'Service Appointments', path: '/service/appointments', module: 'service', icon: 'CalendarDays', group: 'Service', isCore: false, isActive: true, sortOrder: 8 },
  { key: 'warehouses', label: 'Warehouse Management', path: '/warehouses', module: 'warehouses', icon: 'Warehouse', group: 'Master Data', isCore: false, isActive: true, sortOrder: 9 },
  { key: 'sales_orders', label: 'Vehicle Sales Orders', path: '/vehicle-sales/orders', module: 'sales', icon: 'ShoppingCart', group: 'Vehicle Sales', isCore: false, isActive: true, sortOrder: 10 },
  { key: 'quotations', label: 'Vehicle Quotations', path: '/vehicle-sales/quotations', module: 'sales', icon: 'FileText', group: 'Vehicle Sales', isCore: false, isActive: true, sortOrder: 11 },
  { key: 'invoices', label: 'Vehicle Invoices', path: '/vehicle-sales/invoices', module: 'sales', icon: 'ReceiptText', group: 'Vehicle Sales', isCore: false, isActive: true, sortOrder: 12 },
  { key: 'bookings', label: 'Vehicle Bookings', path: '/vehicle-sales/booking', module: 'sales', icon: 'CalendarCheck', group: 'Vehicle Sales', isCore: false, isActive: true, sortOrder: 13 },
  { key: 'dispatch', label: 'Vehicles Dispatch', path: '/dispatch', module: 'dispatch', icon: 'LogOut', group: 'Vehicle Sales', isCore: false, isActive: true, sortOrder: 14 },
  { key: 'vehicle_scan', label: 'Vehicles Scan', path: '/vehicle-sales/barcode-scan', module: 'sales', icon: 'ScanBarcode', group: 'Vehicle Sales', isCore: false, isActive: true, sortOrder: 15 },
  { key: 'part_quotations', label: 'Parts Quotation', path: '/parts-sales/quotations', module: 'sales', icon: 'FileText', group: 'Parts Sales', isCore: false, isActive: true, sortOrder: 16 },
  { key: 'part_bookings', label: 'Parts Bookings', path: '/parts-sales/bookings', module: 'sales', icon: 'LucideCalendarCheck', group: 'Parts Sales', isCore: false, isActive: true, sortOrder: 17 },
  { key: 'part_invoices', label: 'Parts Invoices', path: '/parts-sales/invoices', module: 'sales', icon: 'ReceiptText', group: 'Parts Sales', isCore: false, isActive: true, sortOrder: 18 },
  { key: 'part_scan', label: 'Parts Scan', path: '/parts-sales/barcode-scan', module: 'sales', icon: 'ScanBarcode', group: 'Parts Sales', isCore: false, isActive: true, sortOrder: 19 },
  { key: 'custom_quotations', label: 'Custom Quotations', path: '/custom/quotations', module: 'custom', icon: 'FileText', group: 'Custom Sales', isCore: false, isActive: true, sortOrder: 20 },
  { key: 'custom_bookings', label: 'Custom Bookings', path: '/custom/bookings', module: 'custom', icon: 'CalendarCheck', group: 'Custom Sales', isCore: false, isActive: true, sortOrder: 21 },
  { key: 'custom_invoices', label: 'Custom Invoices', path: '/custom/invoices', module: 'custom', icon: 'ReceiptText', group: 'Custom Sales', isCore: false, isActive: true, sortOrder: 22 },
  { key: 'gatepass_in', label: 'Gate Pass In', path: '/gatepass/in', module: 'gatepass', icon: 'LogIn', group: 'Gate Pass', isCore: false, isActive: true, sortOrder: 23 },
  { key: 'gatepass_out', label: 'Gate Pass Out', path: '/gatepass/out', module: 'gatepass', icon: 'LogOut', group: 'Gate Pass', isCore: false, isActive: true, sortOrder: 24 },
  { key: 'gatepass_verify', label: 'Gate Verify', path: '/gatepass/verify', module: 'gatepass', icon: 'ShieldCheck', group: 'Gate Pass', isCore: false, isActive: true, sortOrder: 25 },
  { key: 'employees', label: 'Employees', path: '/hr/employees', module: 'hr', icon: 'UserRound', group: 'HR & Finance', isCore: false, isActive: true, sortOrder: 26 },
  { key: 'leaves', label: 'Leaves', path: '/hr/leaves', module: 'leaves', icon: 'CalendarDays', group: 'HR & Finance', isCore: false, isActive: true, sortOrder: 27 },
  { key: 'expenses', label: 'Expenses', path: '/hr/expenses', module: 'expenses', icon: 'WalletCards', group: 'HR & Finance', isCore: false, isActive: true, sortOrder: 28 },
  { key: 'ledger', label: 'Ledger', path: '/hr/ledger', module: 'ledger', icon: 'BookOpen', group: 'HR & Finance', isCore: false, isActive: true, sortOrder: 29 },
  { key: 'payroll', label: 'Payroll', path: '/hr/payroll', module: 'payroll', icon: 'HandCoins', group: 'HR & Finance', isCore: false, isActive: true, sortOrder: 30 },
  { key: 'accounts', label: 'Accounts & Petty Cash', path: '/finance/accounts', module: 'accounts', icon: 'Landmark', group: 'HR & Finance', isCore: false, isActive: true, sortOrder: 31 },
  { key: 'lead_master', label: 'Lead Master Data', path: '/lead-master', module: 'lead-master', icon: 'ListTree', group: 'Master Data', isCore: false, isActive: true, sortOrder: 32 },
  { key: 'service_master', label: 'Service Master Data', path: '/service-master', module: 'service-master', icon: 'Settings', group: 'Master Data', isCore: false, isActive: true, sortOrder: 33 },
  { key: 'sales_master', label: 'Sales Master Data', path: '/sales-master', module: 'sales-master', icon: 'PanelTop', group: 'Master Data', isCore: false, isActive: true, sortOrder: 34 },
  { key: 'user_management', label: 'User Management', path: '/admin/users', module: 'users', icon: 'UsersRound', group: 'Management', isCore: false, isActive: true, sortOrder: 35 },
  { key: 'role_management', label: 'Role Management', path: '/admin/roles', module: 'roles', icon: 'LucideUserCheck2', group: 'Management', isCore: false, isActive: true, sortOrder: 36 },
  { key: 'department_management', label: 'Department Management', path: '/admin/departments', module: 'departments', icon: 'Building2', group: 'Management', isCore: false, isActive: true, sortOrder: 37 },
  { key: 'status_management', label: 'Option Management', path: '/admin/statuses', module: 'statuses', icon: 'ListChecks', group: 'Management', isCore: false, isActive: true, sortOrder: 38 },
  { key: 'reports', label: 'Reports', path: '/reports', module: 'reports', icon: 'BarChart3', group: 'Reports', isCore: false, isActive: true, sortOrder: 39 },
  { key: 'data_import', label: 'Data Upload', path: '/data-import', module: 'uploader', icon: 'UploadCloud', group: 'Uploader', isCore: false, isActive: true, sortOrder: 40 },
  { key: 'payment_methods', label: 'Payment Methods', path: '/payment-methods', module: 'payment-methods', icon: 'CreditCard', group: 'ERP Settings', isCore: false, isActive: true, sortOrder: 41 },
  { key: 'settings', label: 'ERP Settings', path: '/settings', module: 'settings', icon: 'SlidersHorizontal', group: 'ERP Settings', isCore: false, isActive: true, sortOrder: 42 },
  { key: 'profile', label: 'Profile', path: '/profile', module: 'profile', icon: 'UserCircle', group: 'Account', isCore: false, isActive: true, sortOrder: 43 },
  { key: 'notification_settings', label: 'Notification Settings', path: '/notification-settings', module: 'notifications', icon: 'Bell', group: 'Account', isCore: false, isActive: true, sortOrder: 44 },
  { key: 'search', label: 'Search', path: '/search', module: 'search', icon: 'Search', group: 'Search', isCore: false, isActive: true, sortOrder: 45 },
  { key: 'email_templates', label: 'Email Templates', path: '/email', module: 'email', icon: 'Mail', group: 'Communication', isCore: false, isActive: true, sortOrder: 46 },
  { key: 'pdf_management', label: 'PDF Management', path: '/pdf-management', module: 'pdf', icon: 'FileDown', group: 'Communication', isCore: false, isActive: true, sortOrder: 47 },
  { key: 'server_management', label: 'Server Management', path: '/server-management', module: 'server-management', icon: 'ServerCog', group: 'Server', isCore: true, isActive: true, sortOrder: 48 },
  { key: 'logs', label: 'Logs', path: '/logs', module: 'logs', icon: 'Activity', group: 'Server', isCore: false, isActive: true, sortOrder: 49 },
];

export default pages;
