import * as XLSX from 'xlsx';

const formatHeader = (key) => String(key || '')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (char) => char.toUpperCase());

const normalizeColumns = (rows) => {
    if (!Array.isArray(rows) || rows.length === 0) return [];
    return Object.keys(rows[0]).map((key) => ({ key, label: formatHeader(key) }));
};

const safeValue = (value) => {
    if (value === null || value === undefined) return '';
    if (typeof value === 'object') return JSON.stringify(value);
    return String(value);
};

const escapeHtml = (value) => safeValue(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const downloadBlob = (blob, filename) => {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};

export const exportReportCsv = ({ rows, reportName, meta = {} }) => {
    if (!rows?.length) return;
    const columns = normalizeColumns(rows);
    const headerLine = columns.map((column) => `"${column.label.replace(/"/g, '""')}"`).join(',');
    const dataLines = rows.map((row) =>
        columns
            .map((column) => `"${safeValue(row[column.key]).replace(/"/g, '""')}"`)
            .join(',')
    );
    const lines = [
        `"${reportName}"`,
        `"Generated At","${new Date().toLocaleString()}"`,
        `"Generated By","${meta.generatedBy || 'System'}"`,
        '',
        headerLine,
        ...dataLines
    ];
    const csv = `\uFEFF${lines.join('\n')}`;
    downloadBlob(new Blob([csv], { type: 'text/csv;charset=utf-8;' }), `${reportName.replace(/\s+/g, '_').toLowerCase()}.csv`);
};

export const exportReportXlsx = ({ rows, reportName, meta = {} }) => {
    if (!rows?.length) return;
    const columns = normalizeColumns(rows);
    const matrix = [
        [reportName],
        ['Generated At', new Date().toLocaleString()],
        ['Generated By', meta.generatedBy || 'System'],
        []
    ];
    const header = columns.map((column) => column.label);
    matrix.push(header);
    rows.forEach((row) => {
        matrix.push(columns.map((column) => row[column.key]));
    });

    const worksheet = XLSX.utils.aoa_to_sheet(matrix);
    worksheet['!cols'] = header.map(() => ({ wch: 22 }));
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Report');
    const content = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
    downloadBlob(
        new Blob([content], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }),
        `${reportName.replace(/\s+/g, '_').toLowerCase()}.xlsx`
    );
};

export const exportReportPdf = ({ rows, reportName, meta = {} }) => {
    if (!rows?.length) return;
    const columns = normalizeColumns(rows);
    const tableHeader = columns.map((column) => `<th>${escapeHtml(column.label)}</th>`).join('');
    const tableRows = rows.map((row) => {
        const cells = columns.map((column) => `<td>${escapeHtml(row[column.key])}</td>`).join('');
        return `<tr>${cells}</tr>`;
    }).join('');

    const html = `
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(reportName)}</title>
  <style>
    body { font-family: Inter, Arial, sans-serif; color: #0f172a; padding: 24px; }
    .header { border-bottom: 2px solid #1e3a8a; margin-bottom: 16px; padding-bottom: 12px; }
    .title { font-size: 24px; font-weight: 700; color: #1e3a8a; margin: 0 0 4px 0; }
    .meta { font-size: 12px; color: #475569; }
    table { width: 100%; border-collapse: collapse; font-size: 11px; }
    th, td { border: 1px solid #cbd5e1; padding: 8px; text-align: left; }
    th { background: #e2e8f0; color: #0f172a; text-transform: uppercase; font-size: 10px; }
    tr:nth-child(even) td { background: #f8fafc; }
    @page { size: A4 landscape; margin: 10mm; }
  </style>
</head>
<body>
  <div class="header">
    <h1 class="title">${escapeHtml(reportName)}</h1>
    <div class="meta">Generated: ${new Date().toLocaleString()}</div>
    <div class="meta">Generated By: ${escapeHtml(meta.generatedBy || 'System')}</div>
  </div>
  <table>
    <thead><tr>${tableHeader}</tr></thead>
    <tbody>${tableRows}</tbody>
  </table>
</body>
</html>`;

    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.open();
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
        printWindow.print();
        printWindow.close();
    }, 300);
};
